controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    joint_effort_controller:
      type: effort_controllers/JointGroupEffortController


joint_effort_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
      - effort
      